split: val
version: airdc_ms2_val
dataset: ms2
data_folder: ./data/MS2
ckpt_path:
  - ms2_972.pth
nickname: AirDC_MS2
howtoval: full
baseline: 0.54
export_to_swanlab: true
epochs: 30
lr: 1e-4
mixed_precision: true
hg_full: false
update_dim: 128
steps_decay: false
volume_att: true
update_with: selective
attention_active: false
cnet_attention: true
D: 50
z_max: 100
num_iters: 4
steps: 0.02
corr_radius: 4
loss_type: l1_l2
train_strategy: iSLDV
training_depth_mask_out_rate: 0.0
mask_rgb_patch_ratio: 0.0
embed_channels: 32
GRU_hidden_dim: 128
down_factor: 4
corr_levels: 2
n_downsample: 2
n_gru_layers: 3
depth_wise: false
crop_type: random
crop_height: 352
crop_width: 1216
owidth: 1216
oheight: 352
volume_fusion: original
convolutional_layer_encoding: std
predict_head: linear_regression
depth_fusion: soft_code
geo_fn_mode: depth_disp
update_mode: rgbd
loss_source: depth
add_noise: false
noise_type: gaussian
noise_std: 0.01
noise_sp_prob: 0.005
confidence_guide: false
model_name: AirDC
lidar_lines: 64
save_result: false
vis_result: false
